-- Tabla de Cortes
CREATE TABLE Cortes (
    CorteID INTEGER PRIMARY KEY AUTOINCREMENT,
    FechaHora DATETIME DEFAULT CURRENT_TIMESTAMP,
    TotalVendido REAL NOT NULL,
    TotalVentas INTEGER NOT NULL
);