# Usa la imagen de SQL Server como base
FROM mcr.microsoft.com/mssql/server:2022-latest

# Establece las variables de entorno necesarias
ENV ACCEPT_EULA=Y
ENV MSSQL_SA_PASSWORD=Cbmwjmkq23  
# Tu contraseña segura para el usuario SA

# Exponer el puerto 1433 para SQL Server
EXPOSE 1433

# Comando para iniciar SQL Server
CMD ["/opt/mssql/bin/sqlservr"]
