name: Build and Push SQL Image to GHCR

on:
  push:
    branches:
      - main

jobs:
  build-dacpac:
    runs-on: windows-latest
    outputs:
      dacpac-path: ${{ steps.upload.outputs.dacpac-path }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3

      - name: Build DACPAC with MSBuild
        run: |
          msbuild Medical.Office.SqlLocalDB/Medical.Office.SqlLocalDB.sqlproj /p:Configuration=Release

      - name: Upload built DACPAC artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: dacpac
          path: Medical.Office.SqlLocalDB/bin/Release/*.dacpac

  build-and-push-image:
    needs: build-dacpac
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download DACPAC artifact
        uses: actions/download-artifact@v4
        with:
          name: dacpac
          path: Medical.Office.SqlLocalDB/

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/medicalofficesql
          tags: |
            type=raw,value=latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./Medical.Office.SqlLocalDB
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
